const IMAGE_MODEL = 'gemini-3.1-flash-image-preview';
const BASE_URL = 'https://generativelanguage.googleapis.com/v1beta';

function getApiKey(): string {
  const key = process.env.GEMINI_API_KEY;
  if (!key) throw new Error('Missing GEMINI_API_KEY');
  return key;
}

export interface GenerateImageResult {
  url: string;
  prompt: string;
  mimeType: string;
}

interface GeminiPart {
  inlineData?: { data: string; mimeType: string };
  text?: string;
}

interface GeminiResponse {
  candidates?: Array<{ content?: { parts?: GeminiPart[] } }>;
  error?: { message?: string; code?: number };
}

async function callImageModel(prompt: string): Promise<GenerateImageResult> {
  const apiKey = getApiKey();
  const url = `${BASE_URL}/models/${IMAGE_MODEL}:generateContent?key=${apiKey}`;

  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        responseModalities: ['IMAGE', 'TEXT'],
      },
    }),
  });

  if (!res.ok) {
    const error = (await res.json().catch(() => ({}))) as GeminiResponse;
    throw new Error(error?.error?.message || `Gemini API error: ${res.status}`);
  }

  const data = (await res.json()) as GeminiResponse;
  const parts = data?.candidates?.[0]?.content?.parts;

  if (!parts?.length) {
    throw new Error('No image generated by Gemini');
  }

  const imagePart = parts.find((p) => p.inlineData);

  if (!imagePart?.inlineData) {
    throw new Error('Gemini response did not contain an image');
  }

  const mimeType = imagePart.inlineData.mimeType || 'image/png';

  return {
    url: `data:${mimeType};base64,${imagePart.inlineData.data}`,
    prompt,
    mimeType,
  };
}

export async function generateImage(prompt: string): Promise<GenerateImageResult> {
  return callImageModel(prompt);
}

export async function generateMultipleImages(
  prompt: string,
  count: number = 4
): Promise<GenerateImageResult[]> {
  const promises = Array.from({ length: count }, (_, i) => {
    const variation = i === 0
      ? prompt
      : `${prompt} (variation ${i + 1}, different composition and angle)`;
    return callImageModel(variation).catch(() => null);
  });

  const results = await Promise.all(promises);
  return results.filter((r): r is GenerateImageResult => r !== null);
}
